### ISSUE TITLE
Can the config.root.sizes() being all equal assert be removed?

### ISSUE THREAD

**Issue by AlgoryxMartinN** [jw007123/hp-Adaptive-Signed-Distance-Field-Octree#2]
At [Config.cpp#L22](https://github.com/jw007123/hp-Adaptive-Signed-Distance-Field-Octree/blob/bc86c51b6358e7d5a424842d9d4619b85cc4d553/Source/HP/Config.cpp#L22).

**Comment by jw007123** [comment]
It has been a while since I worked on this, but from memory if you change the root's sizes, then the values generated by the lookup table 'NormalisedLengthsCalc' need to be scaled appropriately when they're used. Wouldn't be very hard to implement and I could probably do it over the next few days. 

What's the use case, if you don't mind me asking? If this is for work, I've updated the README with a TODO about fixing some bug in the meshing code. If you already have a BVH setup and don't need anything under the Meshing header, then great. Otherwise, that's something else to note. Should be an easy fix as well though.

**Comment by jw007123** [comment]
Just had a look and as a follow on to that comment I think that it actually should be OK to get rid of the check. The internal volume being set to the unit cube should solve the problem as all the nodes are actually cubes. I'll test it tonight and push it to the branch formally if it's fine.

**Comment by AlgoryxMartinN** [comment]
The use-case is for collision detection between spherical particles and a non-convex, possibly hollow, mesh. I want to determine if using a signed distance field instead of testing the particles against the mesh triangles directly will work better and/or faster. The mesh is quite long so being forced to expand the field domain along the shorter axes to equal the longest axis will make it cover a noticeable larger volume. Though if the internal nodes are size-normalized, i.e. appear as non-equilateral cubes (cuboids) when views from the outside but treated as cubes within the octree-space, then  perhaps that doesn't matter much?

I don't think I use anything from the Meshing header, I pretty much just call `SDF::Octree::Create` with a  distance sample function I already have, and then `QueryWithGradient` over and over.

I did some initial testing with a non-cube root AABB and all worked well until I needed to debug something else and that's when I built in Debug mode and hit the assert.

**Comment by jw007123** [comment]
Yeah, that makes sense and I think that removing the assert should be fine. I can't remember ever testing thoroughly on domains that weren't cuboid, but if it's working then it's working and all of the configInvSize stuff etc that is used to handle uniform scaling and translations has generalised to that case. 

Feel free to let me know if there's any more problems. I use this at work for some stuff that we do (well, a templated version of it for 2, 3, 4D etc) and it's nice that somebody else might too.

**Comment by AlgoryxMartinN** [comment]
I will make a few test-cases of simple but long meshes to see if any oddities show up.

Thanks for your work, I would not have gotting this far if I had to do everything from scratch.

**Comment by jw007123** [comment]
Removed the assert in Config.cpp as part of the most recent commit. 

No problem! You should be able to hit >1Mil Query() calls a second with any input SDF/mesh, which is a massive improvement on the basic O(n) or even O(log(n)) query strategies.  If you have any more questions about using/what bits are for, feel free to open a new issue.
